# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(584, 478)
        Registration.setStyleSheet("background-color: rgb(230, 230, 250);")
        self.centralwidget = QtWidgets.QWidget(Registration)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 110, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("font: 75 10pt \"Segoe Script\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(85, 85, 85);\n"
"border-radius: 10;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 200, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("font: 75 10pt \"Segoe Script\";\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(85, 85, 85);\n"
"border-radius: 10;")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 330, 171, 51))
        self.pushButton.setStyleSheet("font: 75 10pt \"Segoe Script\";\n"
"background-color: rgb(204, 204, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 330, 171, 51))
        self.pushButton_2.setStyleSheet("font: 75 10pt \"Segoe Script\";\n"
"background-color: rgb(204, 204, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 10pt \"Segoe Script\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 81, 201))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("data/pict3.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 100, 71, 171))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("data/pict6.png"))
        self.label_3.setObjectName("label_3")
        Registration.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Registration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 584, 26))
        self.menubar.setObjectName("menubar")
        Registration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Registration)
        self.statusbar.setObjectName("statusbar")
        Registration.setStatusBar(self.statusbar)

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Регистрация"))
        self.lineEdit.setText(_translate("Registration", "Логин"))
        self.lineEdit_2.setText(_translate("Registration", "Пароль"))
        self.pushButton.setText(_translate("Registration", "Вход"))
        self.pushButton_2.setText(_translate("Registration", "Регистрация"))
        self.label.setText(_translate("Registration", "Добро пожаловать! Готовы приступить к работе?"))
